export const knownCreditors = [
  // Major Banks & National Lenders
  "BANK OF AMERICA", "CHASE", "JPMORGAN CHASE", "WELLS FARGO", "CITIBANK", "US BANK", "PNC BANK", "REGIONS BANK",
  "TRUIST", "TD BANK", "KEYBANK", "ALLY FINANCIAL", "BMO HARRIS", "FIFTH THIRD BANK", "BANK OF THE WEST", "BBVA", "SUNTRUST",
  "M&T BANK", "FIRST REPUBLIC BANK", "HUNTINGTON NATIONAL BANK", "COMERICA BANK", "SANTANDER BANK", "HSBC", "CAPITAL ONE", "BANK OF NEW YORK MELLON",

  // Credit Cards & Card Issuers
  "AMERICAN EXPRESS", "AMEX", "DISCOVER", "VISA", "MASTERCARD", "CITI CARDS", "BARCLAYCARD", "USAA", "NFCU", "SYNCHRONY BANK", "ELAN FINANCIAL SERVICES",
  "FIRST PREMIER BANK", "MERRICK BANK", "INDIGO", "AVANT", "WELLS FARGO CARD SERVICES", "CAPITAL ONE BANK USA",

  // Credit Unions (Some Major Ones)
  "NAVY FEDERAL CREDIT UNION", "PENFED", "SCHOOLS FIRST FCU", "ALLIANT CREDIT UNION", "VYSTAR", "FIRST TECH FEDERAL CREDIT UNION", "BAXTER CREDIT UNION", "MOUNTAIN AMERICA CREDIT UNION",
  "AMERICA FIRST CREDIT UNION", "STATE EMPLOYEES CREDIT UNION", "GECU", "LOGIX FEDERAL CREDIT UNION",

  // Auto Finance & Lease
  "TOYOTA FINANCIAL", "TOYOTA MOTOR CREDIT", "HONDA FINANCIAL", "AMERICAN HONDA FINANCE", "FORD MOTOR CREDIT", "GM FINANCIAL", "ALLY AUTO", "CAPITAL ONE AUTO FINANCE",
  "NISSAN MOTOR ACCEPTANCE", "HYUNDAI MOTOR FINANCE", "CHRYSLER CAPITAL", "KIA MOTORS FINANCE", "VW CREDIT", "MERCEDES-BENZ FINANCIAL", "BMW FINANCIAL SERVICES", "CARMAX AUTO FINANCE",
  "SANTANDER CONSUMER USA", "WESTLAKE FINANCIAL", "DRIVE FINANCIAL", "AMERICREDIT", "CREDIT ACCEPTANCE CORP",

  // Student Loans & Servicers
  "NAVIENT", "SALLIE MAE", "NELNET", "GREAT LAKES", "MOHELA", "FEDLOAN SERVICING", "AES", "DEPARTMENT OF EDUCATION", "DEPT OF ED", "OSLA", "EDFINANCIAL", "CITIZENS ONE STUDENT LOANS",

  // Mortgage & Home Lenders
  "QUICKEN LOANS", "ROCKET MORTGAGE", "WELLS FARGO HOME MORTGAGE", "CHASE HOME LENDING", "BANK OF AMERICA HOME LOANS", "CITIMORTGAGE", "CALIBER HOME LOANS", "NATIONSTAR MORTGAGE",
  "MR COOPER", "LOANDEPOT", "PNC MORTGAGE", "U.S. BANK HOME MORTGAGE", "FREEDOM MORTGAGE", "PHH MORTGAGE", "FIFTH THIRD MORTGAGE", "DITECH FINANCIAL", "FLAGSTAR BANK",

  // Retail/Store Cards & Financing
  "SYNCHRONY BANK", "COMENITY BANK", "WELLS FARGO FINANCIAL", "CAPITAL ONE RETAIL SERVICES", "CITI RETAIL SERVICES",
  "BEST BUY", "AMAZON", "TARGET", "WALMART", "MACYS", "NORDSTROM", "KOHL'S", "JCPENNEY", "TJX", "GAP", "LOWES", "HOME DEPOT", "SEARS", "BLOOMINGDALE'S", "DILLARD'S", "NEIMAN MARCUS",

  // Buy Now Pay Later / Installment
  "AFIRM", "KLARNA", "AFTERPAY", "ZIP", "SEZZLE", "PAYPAL CREDIT",

  // Telecommunications
  "AT&T", "VERIZON", "T-MOBILE", "SPRINT", "US CELLULAR", "BOOST MOBILE", "METRO PCS", "CRICKET WIRELESS", "COMCAST", "CHARTER", "SPECTRUM", "COX", "DISH NETWORK", "DIRECTV",

  // Utilities & Energy
  "DUKE ENERGY", "SOUTHERN CALIFORNIA EDISON", "PG&E", "CONEDISON", "FLORIDA POWER & LIGHT", "NATIONAL GRID", "DOMINION ENERGY", "SAN DIEGO GAS & ELECTRIC", "PEPCO", "BGE", "XCEL ENERGY",

  // Medical/Health Financing
  "CARE CREDIT", "WELLS FARGO HEALTH ADVANTAGE", "GREEN SKY PATIENT SOLUTIONS",

  // Collections (Common Collection Agencies)
  "MIDLAND CREDIT MANAGEMENT", "PORTFOLIO RECOVERY ASSOCIATES", "LVNV FUNDING", "ENHANCED RECOVERY COMPANY", "CREDIT ONE BANK", "CAVALRY PORTFOLIO SERVICES", "NCO FINANCIAL", "ALLIED INTERSTATE", "PRA GROUP", "CONVERGENT OUTSOURCING", "IC SYSTEM",

  // Other Lenders & Miscellaneous
  "ONE MAIN FINANCIAL", "LENDMARK FINANCIAL", "UPSTART", "SOFI", "LENDINGCLUB", "OPORTUN", "MARCUS BY GOLDMAN SACHS", "DISCOVER PERSONAL LOANS", "LIGHTSTREAM", "AVANT", "EARNEST", "PROSPER",

  // Miscellaneous Retailers
  "APPLE CARD", "SAMS CLUB", "COSTCO", "FINGERHUT", "RAYMOUR & FLANIGAN", "ASHLEY FURNITURE",

  // Credit Bureaus (for reference)
  "EQUIFAX", "EXPERIAN", "TRANSUNION"
];
