// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../supabase/types/supabase';


const supabaseUrl = process.env.SUPABASE_URL as string;
const supabasePublishableKey = process.env.SUPABASE_PUBLISHABLE_KEY as string;

// Import the supabase client in other files like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey);