
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card";
import { DisputeLettersTable } from "./DisputeLettersTable";
import { MailStatus } from "./MailStatus";

interface DisputeItem {
  bureau: string;
  company: string;
  type: string;
  amount: string;
  status: string;
}

interface DisputesTabProps {
  disputeItems: DisputeItem[];
  onBackToOverview: () => void;
}

export function DisputesTab({ disputeItems, onBackToOverview }: DisputesTabProps) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <Card className="lg:col-span-2">
        <CardHeader>
          <CardTitle>Dispute Letters</CardTitle>
          <CardDescription>
            View and manage dispute letters generated by our AI
          </CardDescription>
        </CardHeader>
        <CardContent>
          <DisputeLettersTable disputeItems={disputeItems} />
        </CardContent>
      </Card>
      
      <MailStatus onBackToOverview={onBackToOverview} />
    </div>
  );
}
