// This file is automatically generated. Do not edit it directly unless absolutely necessary for testing workarounds.
// If regenerated, these changes may be overwritten.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use process.env for compatibility with Jest and Node.js environments
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});