// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzeryqigerqalgpsfqam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZXJ5cWlnZXJxYWxncHNmcWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODA0NTMsImV4cCI6MjA2MTQ1NjQ1M30.RoSAJfuovC_Du-d0WgwGa86icTRGcsxUrvNyv3IZGIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);